server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
springdoc:
  version: 1
spring:
  application:
    name: "equilibrium"
  devtools:
    add-properties: false
  webflux:
    base-path: "api/v1/equilibrium/"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  postgresql:
    schema: schpole
    pool:
      initial: 10
      max: 10
  jwt:
    code: "84s8tBfElbwjKXXhFZpqJcW9XUBnydflhF/hxJyH/cE="
  secrets-manager:
    secret-rds: "pole-local-secretrds-CNX"
    secret-email: "pole-send-email"
    cache-size: 300
    cache-time: 2
    endpoint: "http://localhost:4566"
  entries:
    reactive-web:
      person: /person
      classP: /classP
      course: /course
      pay: /pay
      plan: /plan
      planCourses: /planCourses
      userClass: /userClass
      path-base: "api/v1/equilibrium/"

